project:
  type: website
  output-dir: docs
  resources: 
    - "lectures/*.pdf"
    
website:
  title: "STT843 Multivariate Data Analysis"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: lectures.qmd
        text: Lectures
      - href: labs.qmd
        text: Labs
      - href: assignments.qmd
        text: Assignments

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css

editor: visual
